#!/bin/bash

export BANO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DATA_DIR=/media/Data/osm/GitHub/bano_data
export LOG_DIR=$DATA_DIR/log
export DOWNLOAD_DIR=$DATA_DIR/download
export IMPOSM_CACHE_DIR=$DATA_DIR/bano_imposm_cache
export BANO_CACHE_DIR=$DATA_DIR/bano_cache
export BAN_CACHE_DIR=$DATA_DIR/ban_cache
export CADASTRE_CACHE_DIR=$DATA_DIR/cadastre_cache
export BAL_CACHE_DIR=$DATA_DIR/bal_cache
export EXPIRE_TILES_DIR=$DATA_DIR/expire_tiles
export CSV_DIR=$DATA_DIR/csv_insee
export EXPORT_SAS_DIR=$DATA_DIR/sas_web
export EXPORT_WEB_DIR=$DATA_DIR/work/bano.openstreetmap.fr/www/web/data/
export TMP_DIR=$DATA_DIR/tmp
export SCHEMA_CIBLE=public
export LANG=fr_FR.UTF-8
