#!/bin/bash

export BANO_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export DATA_DIR=/media/NFS/DD_Data/projets/osm/GitHub/bano_data
export LOG_DIR=$DATA_DIR/log
export LOCK_DIR=$BANO_DIR/lock
export DOWNLOAD_DIR=$DATA_DIR/download
export IMPOSM_CACHE_DIR=$DATA_DIR/bano_imposm_cache
export BANO_CACHE_DIR=$DATA_DIR/bano_cache
export BAN_CACHE_DIR=$DATA_DIR/ban_cache
export CADASTRE_CACHE_DIR=$DATA_DIR/cadastre_cache
export BAL_CACHE_DIR=$DATA_DIR/bal_cache
export EXPIRE_TILES_DIR=$DATA_DIR/expire_tiles
export CSV_DIR=$DATA_DIR/csv_insee
export COG_DIR=$DATA_DIR/cog
export EXPORT_SAS_DIR=$DATA_DIR/sas_web
export EXPORT_WEB_DIR=$DATA_DIR/work/bano.openstreetmap.fr/www/web/data/
export TMP_DIR=$DATA_DIR/tmp
export SCHEMA_CIBLE=public
export LANG=${LANG:-fr_FR.UTF-8}
export PARALLEL_JOBS=${PARALLEL_JOBS:-4}


POSTGRES_USER=${POSTGRES_USER:-cadastre}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ololol}
POSTGRES_HOST=${POSTGRES_HOST:-localhost}
POSTGRES_PORT=${POSTGRES_PORT:-5432}

POSTGRES_DB_BANO=${POSTGRES_DB:-bano}
POSTGRES_DB_CADASTRE=${POSTGRES_DB:-cadastre}

export PGCON_BANO="$POSTGRES_USER${POSTGRES_PASSWORD:+:$POSTGRES_PASSWORD}@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB_BANO"
export pgsql_BANO="psql postgresql://${PGCON_BANO} -v ON_ERROR_STOP=1"
export PG_BANO="host='$POSTGRES_HOST' port=$POSTGRES_PORT dbname='$POSTGRES_DB_BANO' user='$POSTGRES_USER' ${POSTGRES_PASSWORD:+password='$POSTGRES_PASSWORD'}"
